#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_PORT 2417
#define DEFAULT_THREADS_COUNT 10
#define DEFAULT_PACKET_SIZE 1024
#define DEFAULT_DESTINATION_ADDRESS "127.0.0.1"
#define DEFAULT_FILE_PATH "./CMakeCache.txt"
#define DEFAULT_WORK_MODE "sender"

#define WORK_MODE_RECEIVER "receiver"
#define WORK_MODE_SENDER "sender"

#endif // CONSTANTS_H
